### ISSUE TITLE
Support <abbr> and <acronym>

### ISSUE THREAD

**Issue by alexislefebvre** [xz/new.css#59]
I suggest to highlight these tags.

Bootstrap 3 used this style to add a cursor and a bottom border:

```css
abbr[title] {
    cursor: help;
    border-bottom: 1px dotted #999999;
}
```
